### ISSUE TITLE
v1.0.0 roadmap

### ISSUE THREAD

**Issue by antonk52** [antonk52/swaggerlint#19]
- [x] Define the package API.
  `swaggerlint` package should export `swaggerlint` function & utility types
- [x] `extends` config feature. Similar to `eslint`/`babel`. (#20)
- [ ] A built in strict preset with all rules enabled aka `hard-mode`.
- [x] second setting argument
  ie `['camel', {query: 'snake', 'header': 'kebab', ignore: ['words', 'TO', 'IgNoRe']}]`, where the first item is the default for any omitted properties in the second item. (#21)
  - [x] `object-properties-casing` - settings should include `ignore`
  - [x] `parameter-casing` - settings should include `ignore`, `body`, `path`, `query`, `header`, `formData`
- [ ] Plugins API.
  Should mimic API for eslint, babel and postcss.
- [x] WEB APP with swaggerlint validations. An easy way to try it out.
  - [swaggerlint-playground](https://swaggerlint-playground.now.sh/)
  - [repository](https://github.com/antonk52/swaggerlint-playground)
- [ ] DOCS:
    * [ ] Key features of swaggerlint in the readme.md. A draft:
        - Familiar visitor API (like Eslint, Babel and PostCSS)
        - API style oriented instead of validation
    * [ ] Correct and incorrect samples for every rule
    * [x] how to write and add your own rule
